# -*- coding: utf-8 -*-
"""Codechef_may_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaClwNb6FDTjsIhAX_0u43l5wcp98jW-
"""

#1. JOHNY

t = int(input())
for _ in range(t):
    n = int(input())
    a = list(map(int, input().split()))
    k = int(input())
    song = a[k - 1]
    a.sort()
    for i in range(n):
        if a[i] == song:
            print(i + 1)
            break

#2.TABLET

t = int(input())
for _ in range(t):
    n, b = map(int, input().split())
    area = 0
    for _ in range(n):
        w, h, p = map(int, input().split())
        if p <= b:
            if w * h > area:
                area = w * h
    if area == 0:
        print("no tablet")
    else:
        print(area)

#3.LECANDY

t = int(input())
for _ in range(t):
    n, c = map(int, input().split())
    a = list(map(int, input().split()))
    if sum(a) <= c:
        print("Yes")
    else:
        print("No")

#4.SALARY

t = int(input())
for _ in range(t):
    n = int(input())
    w = list(map(int, input().split()))
    print(sum(w) - n * min(w))

#5. STONES

# cook your dish here
t = int(input())
for _ in range(t):
    J = input().strip()
    S = input().strip()
    count = 0
    for ch in S:
        if ch in J:
            count += 1
    print(count)

#6. FLOW017

t=int(input())
for i in range(0,t):
    a,b,c=map(int,input().split())
    n=[a,b,c]
    n.sort()
    print(n[-2])

#7. FLOW006

t=int(input())
for i in range(0,t):
    n=input()
    sum=0
    for d in n:
        sum = sum +int(d)
    print(sum)

#8. LAPIN

t=int(input())
for i in range(0,t):
    S = input().strip()
    mid = len(S) // 2
    if sorted(S[:mid]) == sorted(S[-mid:]):
        print("YES")
    else:
        print("NO")

#9. VOWELTB

C=input().strip()
if C in 'aeiouAEIOU' :
    print("Vowel")
else:
    print("Consonant")

#10.  FLOW006

t=int(input())
for i in range(0,t):
    n=input()
    sum=0
    for d in n:
        sum = sum +int(d)
    print(sum)

#11. NOTINCOM

t=int(input())
for i in range(0,t):
    n,m=map(int,input().split())
    a=set(map(int,input().split()))
    b=set(map(int,input().split()))
    print(len(a&b))

#12. LUCKYSTR

k, n = map(int, input().split())
fav = [input() for i in range(k)]
for i in range(n):
    s = input()
    good = len(s) >= 47
    for f in fav:
        if f in s:
            good = True
    if good:
        print("Good")
    else:
        print("Bad")

#13. TEST

while True:
    n=int(input())
    if n==42:
        break;
    print(n)

#14. FCTRL2

t=int(input())
for i in range(0,t):
    n=int(input())
    fact=1
    for i in range(1,n+1):
        fact=fact*i
    print(fact)

#15. PALL01

t=int(input())
for i in range(t):
    n=input()
    if(n[::-1]==n):
        print("wins")
    else:
        print("loses")

#16. LUCKYFR

t = int(input())
for i in range(t):
    n = input()
    print(n.count('4'))

#17. LOW007

t=int(input())
for i in range(0,t):
    n=input()
    a= n[::-1]
    print(int(a))

#18. FLOW007

t=int(input())
for i in range(0,t):
    n=input()
    a= n[::-1]
    print(int(a))

#19. FLOW009

t=int(input())
for i in range(0,t):
    quantity, price = map(int, input().split())
    total = quantity * price
    if quantity > 1000:
        total = total * 0.90
    print(total)

#20. FLOW014

t=int(input())
for i in range(t):
    h,c,t=input().split()
    h=int(h)
    c=float(c)
    t=int(t)
    if (h>50 and c<0.7 and t>5600):
        print(10)
    elif (h>50 and c<0.7):
        print(9)
    elif (c<0.7 and t>5600):
        print(8)
    elif (h>50 and t>5600):
        print(7)
    elif (h>50 or c<0.7 or t>5600):
        print(6)
    else:
        print(5)

#21. FLOW013

t=int(input())
for i in range(t):
    a,b,c=map(int,input().split())
    s=a+b+c
    if s==180:
        print("YES")
    else:
        print("NO")

#22. FLOW011

t=int(input())
for i in range (t):
    s=int(input())
    if s<1500:
        HRA=10*s/100
        DA=90*s/100
        g=s+HRA+DA
    else:
        HRA=500
        DA=98*s/100
        g=s+HRA+DA
    print(g)

#23. FLOW004

t=int(input())
for i in range(0,t):
    n=input()
    a=int(n[0])
    s=int (n[-1])
    print(a+s)

#24. FSQRT

import math
t=int(input())
for i in range (0,t):
    n=int(input())
    s=math.isqrt(n)
    print(s)

#25. INTEST

(n, k) = map(int, input().split())
ans = 0
for i in range(n):
	x = int(input())
	if x % k == 0:
		ans += 1
print(ans)

#26. START01

n=int(input())
print(n)

#27. FLOW002

t=int(input())
for i in range(0,t):
    a,b=map(int,input().split())
    print(a%b)

#28. FLOW001

t = int(input())
for i in range(0,t):
    a,b = map(int,input().split())
    # write your code here
    print(a+b)

#29. TRICHECK

a,b,c=list(map(int, input().split()))
if (a+b)>c and (b+c)>a and (c+a)>b:
    print("Yes")
else:
    print("No")

#30. AMR15A

n=int(input())
ready=0
notready=0
num=list(map(int,input().split()))
for i in num:
    if(i%2==0):
        ready+=1
    else:
        notready+=1
if n==1:
    print("READY FOR BATTLE")
elif(ready>notready):
    print("READY FOR BATTLE")
else:
    print("NOT READY")