# -*- coding: utf-8 -*-
"""python_technical_practice_full_concepts_2026 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zt2S1-43gCPG8vJVtXYsC6p2VYwoAywM
"""

#1. palindrome

s=input()
if(s[::-1]==s):
  print("palindrome")
else:
  print("not palindrome")

#2. factorial

n=int(input())
fact=1
for i in range(1,n+1):
  fact=fact*i
print(fact)

#3. largest number

a=int(input())
b=int(input())
if(a>b):
  print("a is largest")
else:
  print("b is largest")

#4. typecasting

a="10"
b=int(a)
print(type(b))

#5. armstrong number

n=int(input())
length=len(str(n))
a=0
b=n
while(b>0):
  d=b%10
  a=a+d**length
  b=b//10
if(a==n):
  print("armstrong")
else:
  print("not armstrong")

#6. prime number

start = int(input("Enter start number: "))
end = int(input("Enter end number: "))
for num in range(start, end + 1):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            print(num)

'''for num in range(1,51):
  for i in range(2,num+1):
    if(num%i==0):
      break
  if(num==i):
    print(num)'''

#7. degree conversion

'''c=float(input())
f=(c*9/5)+32
print(f)'''

f=float(input())
c=(f-32)*5/9
print(c)

#8. swap without third variable

a=int(input("a is :"))
b=int(input("b is : "))
a,b=b,a
print("after swap:")
print("a=",a)
print("b=",b)

#9. fibonacii

n=int(input())
a=0
b=1
for i in range(n):
  print(a)
  c=a+b
  a=b
  b=c

#10. average of three numbers

a,b,c = map(int,input().split())
avg= (a+b+c)/3
print (avg)

#11. vovels and count

s=input()
count=0
for ch in (s):
  if ch in "aeiouAEIOU":
    print(ch)
    count=count+1
print("count :",count)

#12. print right angled triangle

row=int(input())
for i in range(1,row+1):
  for j in range(i):
    print("*", end= " ")
  print()

#13. GCD / LCM

a=int(input())
b=int(input())
x=a
y=b
while b!=0:
  a=b
  b=a%b
print("gcd", a)
n=(x*y)//a
print("lcm:", n)

#14. largest and smallest num

n=list(map(int,input().split()))
print("max: ",max(n) )
print("min: ",min(n))

#15. swapping

a= int(input())
b= int(input())
temp=a
a=b
b=temp
print("a :",a)
print("b :",b)

#16. count


n= int(input())
count=0
while n != 0 :
  n=n//10
  count=count+1
print(count)

#17. +ve,-ve or 0

n=int(input())
if n>0:
  print("+ve")
elif n<0:
  print("-ve")
else:
  print("0")

#18. leap year

n=int(input())
if ((n%4==0 and n%100!=0) or n %400==0):   #or only n%4==0 is used
  print("leap year")
else:
  print("not leap year")

#19. even or odd

n=int(input())
if n%2==0:
  print ("even")
else:
  print ("odd")

#20. anagram

s1=input()
s2=input()
if (sorted(s1)==sorted(s2)):
  print("anagram")
else:
  print("not anagram")

#21. number pattern

n=6
for i in range (1,n+1):
  for j in range (1,i+1):
    print(j,end= "")
  print()

#22. * pattern

n=6
for i in range (1,n+1):
  for j in range (n-i):
    print("*",end= "")
  print()

#23. reverse * pattern

n=int(input())
for i in range(n):
  print(" "*i+"* "*(n-i))

#24. diamond pattern

n=4
for i in range (1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range (n-1,0,-1):
  print(" "*(n-i)+"* "*i)

#25. triangle

n=4
for i in range (1,n+1):
  print(" "*(n-i)+"* "*i)

#26. largest 3rd numbers without using if else

n=list(map(int,input().split()))
n.sort()
print (n[-3])

#27. Repeated Number Triangle

row=int(input())
for i in range(1,row+1):
    for j in range(i):
        print(i,end="")
    print()

#28. alphabet

n=int(input())
for i in range(1,n+1):
  for j in range(i):
    print(chr(65+j),end=" ")
  print()

#29. classes & object

class student:
  def __init__(self,name,age):
    self.name=name  # attribute
    self.age=age
  def display(self):
    print("name :",self.name)
    print("age :", self.age)
obj= student("RAJU",3)
obj.display()     # method

'''
#30. inheritance

class father:
  def bike (self):
    print("father has bike")
class son(father):   # in son it check for bike
  def cycle(self):
    print("son has cycle")   # bike not found so move to father
obj=son()
obj.bike() # method
'''

class father :
  def property (self):
    print("father property")
class son (father):
  pass
obj= father()
obj.property()

#31. Polymorphism ( METHOD OVERIDING)

class animal:
  def sound(self):   # uses same method
    print("animal makes sound")
class dog(animal):
  def sound(self):
    print("dog barks")
obj = dog()
obj.sound()

#32. polymorphism ( OVERLOADING )

class multiply:
  def product (self, a=None, b=None, c=None):  # None keyword
    if a and b and c:
      print("produce: ",a*b*c)
    elif a and b:
      print("product: ",a*b)
    else:
      print("invalid input")
obj=multiply()
obj.product(2,3)
obj.product(2,3,4)

#33. abstraction

class bank:
  def __init__(self):
    self.__balance=5000  # data hiding [ uses __ private variables ]
  def show_balance(self):
    print("balance:",self.__balance)
obj= bank()
obj.show_balance()

#34. number is reverse both should be prime

n=int(input())
rev =int(str(n)[::-1])
print(rev)
if (n%2!=0 and rev%2!=0 ):
  print("not prime")
else:
  print("prime")

#35. adam number rev(sq of num)==sq(rev of num)

n=int(input())
rev =int(str(n)[::-1])
print(rev)
a=int(str(n**2)[::-1])
b=rev**2
if (a==b):
  print("adam number")
else:
  print("not adam number")

#36. CIRCULAR PRIME ( all rotation of number should be prime)

n = input()
for i in range(len(n)):
    r = n[i:] + n[:i]
    num = int(r)
    c = 0
    for j in range(1, num + 1):
        if num % j == 0:
            c = c + 1
    if c == 2:
        print(r, "Prime")
    else:
        print(r, "Not Prime")

#37 #1. scenario based problems:
'''1. AI Message Recovery System
Quantum Communication Center
A quantum communication satellite receives encrypted messages from deep-space probes.
Due to signal corruption, one character in a message may be incorrect.
Scientists need to determine whether the message can become a perfect mirror pattern (palindrome) by removing exactly one character.
If possible, print "YES", otherwise print "NO".
Input Format
Single string s
Constraints
•	1 <= length of s <= 10^5
Output Format
Print "YES" or "NO".
Sample Input
abca
Sample Output
YES
Explanation
Removing 'b' produces "aca", which is a palindrome.
'''


s=input()
count=0
for i in range(len(s)):
  st=s[:i]+s[i+1:]
  if(st==st[::-1]):
    print("YES")
    break
  else:
    count+=1
if(count==len(s)):
  print("NO")
else:
  pass

#38
'''2. Missing Sensor Detection System
Smart Factory Monitoring Network
A smart manufacturing plant contains sensors numbered from 1 to N.
During data collection, the monitoring server notices that exactly one sensor failed to report its reading.
Engineers must identify the missing sensor ID.

Input Format
First line contains integer N
Second line contains N-1 sensor IDs
Constraints
•	1 <= N <= 10^5
Output Format
Print missing sensor ID.
Sample Input
5
1 2 3 5
Sample Output
4
'''


n=int(input())
num = map(int,input().split())
sum=1
while sum in num:
  sum=sum+1
print(sum)

#39
'''3. Duplicate Product Detection Engine
E-Commerce Inventory Platform
An online marketplace receives a list of product IDs uploaded by warehouse managers.
Due to synchronization errors, some products may appear more than once.
Without converting the list into a set, determine whether duplicate product IDs exist.
________________________________________
Input Format
Product IDs separated by spaces.
Sample Input
101 102 103 104 102
Sample Output
Duplicate Found
'''

num = input().split()
for i in num:
    if num.count(i) > 1:
        print("Duplicate Found")
        break
else:
    print("No Duplicate")

#40
'''4. Trending Keyword Analyzer
Social Media Intelligence Engine
A social media company tracks millions of hashtags daily.
The analytics engine must identify the most frequently used hashtag.
If multiple hashtags have the same frequency, the system should choose the alphabetically smallest hashtag.

Input Format
Single line containing hashtags separated by spaces.
Sample Input
apple banana apple banana cat
Sample Output
apple
Explanation
Both "apple" and "banana" appear twice.
Alphabetically, "apple" comes first.
'''

num=list(input().split())
num.sort()
itemdict={}
for n in num:
  itemdict[n]=num.count(n)
values=list(itemdict.values())
keys=list(itemdict.keys())
for i in range(len(values)):
  if(values[i]==max(values)):
    print(keys[i])
    break
print(itemdict)

#41
'''5. Banking Fraud Prevention System
Secure Transaction Monitoring Engine
A digital bank uses an automated fraud prevention system.
Customers are allowed to withdraw money only if their remaining balance stays above ₹1000.
Create a BankAccount class and determine whether a withdrawal can be processed safely.
If the balance would drop below ₹1000, print "Transaction Denied".

Input Format
First line contains current balance.
Second line contains withdrawal amount.
Sample Input
5000
4500
Sample Output
Transaction Denied
Explanation
Remaining balance = ₹500
Since ₹500 < ₹1000, the transaction is blocked.

'''


s=int(input())
r=int(input())
p=s-r
if p<1000 :
  print("Transaction Denied")
else:
  pass

#42
'''6. Cybersecurity Access Violation Detector
Enterprise Security Platform
A multinational company maintains two sets:
•	Authorized employee IDs
•	Employees who attempted access
The security system must identify unauthorized access attempts.

Input Format
First line contains authorized employee IDs.
Second line contains attempted employee IDs.
Sample Input
101 102 103 104
101 103 105 106
Sample Output
Unauthorized Users = {105, 106}
'''


s1=list(input().split())
s2=list(input().split())
a=[]
for i in s2:
  if i in s1:
    pass
  else:
    a.append(i)
print(a)

#43
'''7. Rocket Launch Eligibility Checker
Space Mission Control Center
A spacecraft can launch only if:
•	Fuel ≥ 5000 liters
•	Payload ≤ 1000 kg
Create a function that determines whether the rocket is eligible for launch.

Input Format
Fuel amount
Payload weight
Sample Input
6000
900
Sample Output
Launch Approved
'''

f=int(input())
p=int(input())
if f>=5000 and  p<=1000:
  print("Launch Approved")
else:
  print("launch denied")

#44
'''8.Aircraft Collision Warning System
Air Traffic Control Network
Two aircraft positions are represented as coordinate tuples.
The warning system calculates the distance between them.
If the distance is less than 10 km, print "Collision Risk".
Otherwise, print "Safe".

Input Format
First aircraft coordinates (x1, y1)
Second aircraft coordinates (x2, y2)
Sample Input
(2,3)
(5,7)
Sample Output
Collision Risk
'''


x1, y1 = eval(input())
x2, y2 = eval(input())
d = (((x2 - x1) ** 2 + (y2 - y1) ** 2))**(1/2)
if d < 10:
    print("Collision Risk")
else:
    print("Safe")