# -*- coding: utf-8 -*-
"""TITANIC_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11g5pazHXZLfS1zEIyOMf5Syexk7Fno_r
"""

import os
os.environ['KAGGLE_USERNAME']='sushi'
os.environ['KAGGLE_KEY']='KGAT_6773d77c04cfecab58761005313f4c45'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

!unzip /content/titanic-dataset.zip -d /content/titan

import pandas as pd
df = pd.read_csv("/content/titanic-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))
print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

print(df.columns)

print(df['Survived'])

df.drop('Fare', axis=1, inplace=True)
print(df)

print(df['Age'].mean())

df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)
print(df[['Age']].head(10))
print(df['Age'].isnull().sum())

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

print(df['Embarked'].head(10))
print(df['Embarked'].isnull().sum())

df.isnull().sum()

df['HasCabin'] = df['Cabin'].notnull().astype(int)
df.drop('Cabin', axis=1, inplace=True)

df.isnull().sum()

df.drop_duplicates(inplace=True)
print(df)

df['Sex'] = df['Sex'].map({'male':0, 'female':1})
print(df)

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
print(df)

print(df)

import matplotlib.pyplot as plt
plt.boxplot(df['Pclass'])
plt.title('Outlier detection using BoxPlot (Pclass)')
plt.ylabel('Fare')
plt.show()

df=pd.get_dummies(df,columns=['Embarked'],drop_first=True)

print(df)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix ,classification_report

x=df.drop(['Survived','Name', 'Ticket'],axis=1)
y=df['Survived']

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
print("Model Trained")
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Confusion Matrix:")
print(cm)
print("Classification Report:")
print(report)